# Generated by Django 3.2.4 on 2021-09-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='document',
            field=models.FileField(upload_to='media/documents'),
        ),
    ]
