# Generated by Django 3.2.4 on 2021-09-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_apply_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='media/documents'),
        ),
    ]
